Option Explicit
' This module defines a set of public constants that are used to embed meta data in
'  Excel files generated by this code.
' This module must be updated whenever the code is changed.
Public Const CODE_VERSION As String = "1.0"
Public Const CODE_DATE As Date = "2017-03-14"
Public Const CODE_AUTHOR As String = "Michael Maguire"
